### ISSUE TITLE
Consider Adding VBench

### ISSUE THREAD

**Issue by ziqihuangg** [ChenHsing/Awesome-Video-Diffusion-Models#10]
Hi, thanks for collecting a list of benchmark and metrics. Would you consider adding the Text-to-Video benchmark "VBench"?

**VBench: Comprehensive Benchmark Suite for Video Generative Models**
arXiv: https://arxiv.org/abs/2311.17982
website: https://vchitect.github.io/VBench-project/
code: https://github.com/Vchitect/VBench
video: https://www.youtube.com/watch?v=7IhCC8Qqn8Y
huggingface: https://huggingface.co/spaces/Vchitect/VBench_Leaderboard

**Comment by ChenHsing** [comment]
Thank you very much for your suggestions; we have already incorporated your great work. If you find this survey/repo helpful, perhaps you could consider citing this survey in your final version~

**Comment by ziqihuangg** [comment]
Thanks a lot! We will add your survey in our next arXiv version.
