### ISSUE TITLE
Evalcrafter is open-sourced😜

### ISSUE THREAD

**Issue by Yaofang-Liu** [ChenHsing/Awesome-Video-Diffusion-Models#13]
Evalcrafter is open-sourced, it’s nice of you to update. Thanks!

Webpage: https://evalcrafter.github.io
GitHub: https://github.com/evalcrafter/EvalCrafter

Many thanks for your awesome list!!!

**Comment by ChenHsing** [comment]
I have updated it in my repo, it would be very nice if you could consider adding a citation of our survey in your next version.

**Comment by Yaofang-Liu** [comment]
Many thanks for your help. You really did a nice work and we will consider cite it in our next version.
