### ISSUE TITLE
Hi! Could you please add a new dataset?🙋‍

### ISSUE THREAD

**Issue by Yaofang-Liu** [ChenHsing/Awesome-Video-Diffusion-Models#16]
We have released a text-2-video dataset named ECTV, please take a look at:
Dataset: https://huggingface.co/datasets/RaphaelLiu/EvalCrafter_T2V_Dataset
Paper: https://arxiv.org/abs/2310.11440
GitHub: https://github.com/evalcrafter/EvalCrafter

Many thanks for your awesome list!!!

**Comment by ChenHsing** [comment]
Thanks for your attention, I have added it. It will be very nice if you could consider adding a citation of our survey in your final version.

**Comment by Yaofang-Liu** [comment]
Thanks for your help. We will update a new version in the near future and will consider it.
