### ISSUE TITLE
Translation on Zhihu

### ISSUE THREAD

**Issue by Dai-Wenxun** [ChenHsing/Awesome-Video-Diffusion-Models#4]
Thank you for your excellent work for VDM! Out of respect for your efforts, I translated it on Zhihu. Sincerely hope that your work garners further recognition and appreciation.
https://zhuanlan.zhihu.com/p/661860981

**Comment by ChenHsing** [comment]
We sincerely thank you for your hard work in translation and hope to contribute together to the community.
