### ISSUE TITLE
Request to Include Our Relevant Work in Your Survey on Video Diffusion Models

### ISSUE THREAD

**Issue by jaejun-yoo** [ChenHsing/Awesome-Video-Diffusion-Models#44]
Dear Authors,

I hope this email finds you well. I recently came across your comprehensive survey paper with this companion GitHub repository, which I found them to be an insightful and valuable resource for the community.

However, I noticed that our paper, "STREAM: Spatio-TempoRal Evaluation and Analysis Metric for Video Generative Models" (https://arxiv.org/abs/2403.09669), which was published on arXiv in March and has been accepted to ICLR 2024, is not included in your survey nor in the Github. Given its relevance, I believe it would be a valuable addition to your survey.

TL;DR:
Our paper introduces STREAM, the first video evaluation metric designed to independently evaluate spatial and temporal aspects, offering comprehensive analysis unconstrained by video length. STREAM addresses limitations of current metrics like FVD, providing more stable and human-aligned evaluations.

Abstract of our paper:

Image generative models have made significant progress in generating realistic and diverse images, supported by comprehensive guidance from various evaluation metrics. However, current video generative models struggle to generate even short video clips, with limited tools that provide insights for improvements. Current video evaluation metrics are simple adaptations of image metrics by switching the embeddings with video embedding networks, which may underestimate the unique characteristics of video. Our analysis reveals that the widely used Frechet Video Distance (FVD) has a stronger emphasis on the spatial aspect than the temporal naturalness of video and is inherently constrained by the input size of the embedding networks used, limiting it to 16 frames. Additionally, it demonstrates considerable instability and diverges from human evaluations. To address the limitations, we propose STREAM, a new video evaluation metric uniquely designed to independently evaluate spatial and temporal aspects. This feature allows comprehensive analysis and evaluation of video generative models from various perspectives, unconstrained by video length. We provide analytical and experimental evidence demonstrating that STREAM provides an effective evaluation tool for both visual and temporal quality of videos, offering insights into area of improvement for video generative models. To the best of our knowledge, STREAM is the first evaluation metric that can separately assess the temporal and spatial aspects of videos. Our code is available at this URL.

We would be grateful if you could consider including a reference to our work in your survey. We believe that it will provide additional value and a more comprehensive overview of the current state of video generative model evaluation metrics.

Thank you for your consideration, and I look forward to your response.

Best regards,
Jaejun

**Comment by ChenHsing** [comment]
Sorry for the late reply. This is indeed a great job, and I have already added it in our website.
