### ISSUE TITLE
Add githhub url to VMC (Video-Motion-Customization)

### ISSUE THREAD

**Issue by HyeonHo99** [ChenHsing/Awesome-Video-Diffusion-Models#8]
Thanks a lot for your efforts in categorizing and staying tuned even for recently published papers.

I would like to ask you to add github url to VMC paper.
In category of **Motion-guided Video Generation**
The paper **VMC: One-Shot Video Motion Customization using Temporal Attention Adaption for Text-to-Video Diffusion Models**

The github link is this: https://github.com/HyeonHo99/Video-Motion-Customization

Thank you!

**Comment by ChenHsing** [comment]
Thank you very much for your suggestions; we have already incorporated it. If you find this survey/repo helpful, perhaps you could consider citing this survey in your final version~

**Comment by HyeonHo99** [comment]
Thank you!
I will try not to forget citing your survey paper in the final version of VMC paper.
Moreover, in the future works on video diffusions, I will try citing your work(s).
